name: remove_unused_localizations_keys
description: "A Flutter package to clean unused localization keys from .arb files."
version: 0.0.1
homepage: https://github.com/abdoelmorap/remove_unused_localizations_keys
repository: https://github.com/abdoelmorap/remove_unused_localizations_keys
issue_tracker: https://github.com/abdoelmorap/remove_unused_localizations_keys/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
