name: remove_unused_localizations_keys
description: "A Flutter package to clean unused localization keys from .arb files."
version: 0.0.5
homepage: https://github.com/abdoelmorap/remove_unused_localizations_keys
repository: https://github.com/abdoelmorap/remove_unused_localizations_keys
issue_tracker: https://github.com/abdoelmorap/remove_unused_localizations_keys/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  remove_unused_localizations_keys: remove_unused_localizations_keys



dependencies:
  yaml: ^3.1.3

