name: remove_unused_localizations_keys
description: "A Flutter package to clean unused localization keys from .arb files."
version: 0.0.30
homepage: https://github.com/abdoelmorap/remove_unused_localizations_keys
repository: https://github.com/abdoelmorap/remove_unused_localizations_keys
issue_tracker: https://github.com/abdoelmorap/remove_unused_localizations_keys/issues

publisher:
  name: abdelrhmantolba.online
  email: AbdelrahmanTolba@protonmail.com
  website: https://abdelrhmantolba.online
  country: EG

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  remove_unused_localizations_keys: remove_unused_localizations_keys

screenshots:
  - description: The remove_unused_localizations_keys package logo.
    path: screenshots/logo.png

dependencies:
  yaml: ^3.1.3

